name: Update lists

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "36 0/3 * * *"
  workflow_dispatch:

concurrency: global

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go compiler
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.22.0"
      - name: Run
        run: go run bsky.watch/list-updater@latest --config=config.yaml
        env:
          GITHUB_SECRETS_JSON: ${{ toJson(secrets) }}
